import Sidebar from "@/components/layout/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className="flex">
          <Sidebar />
          <div className="bg-[#FAFAFA] w-full h-screen overflow-y-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
